/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KcervenkaAmbulanceWlList {
    }
}
declare global {
    interface HTMLKcervenkaAmbulanceWlListElement extends Components.KcervenkaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLKcervenkaAmbulanceWlListElement: {
        prototype: HTMLKcervenkaAmbulanceWlListElement;
        new (): HTMLKcervenkaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "kcervenka-ambulance-wl-list": HTMLKcervenkaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface KcervenkaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "kcervenka-ambulance-wl-list": KcervenkaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kcervenka-ambulance-wl-list": LocalJSX.IntrinsicElements["kcervenka-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLKcervenkaAmbulanceWlListElement>;
        }
    }
}
